# Generated by Django 4.0.4 on 2022-05-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_of_beds', models.IntegerField()),
                ('no_of_guests', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='property/')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('amenities', models.TextField(max_length=500)),
                ('highlights', models.TextField()),
                ('price', models.FloatField()),
                ('reviews', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('S', 'Studio'), ('F', 'Flat'), ('H', 'House')], max_length=1)),
            ],
            options={
                'verbose_name': 'Property Category',
                'verbose_name_plural': 'Property Categories',
            },
        ),
        migrations.DeleteModel(
            name='Apt',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.propertycategory'),
        ),
    ]
