# Generated by Django 4.0.4 on 2022-06-12 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_of_beds', models.IntegerField()),
                ('no_of_guests', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(blank=True, upload_to='images/properties')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('attractions', models.ManyToManyField(blank=True, to='amenities.attractions')),
                ('bathroom', models.ManyToManyField(blank=True, to='amenities.bathroom')),
                ('bedroom', models.ManyToManyField(blank=True, to='amenities.bedroom')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.city')),
                ('cleaning', models.ManyToManyField(blank=True, to='amenities.cleaning')),
                ('entertainment', models.ManyToManyField(blank=True, to='amenities.entertainment')),
                ('facilities', models.ManyToManyField(blank=True, to='amenities.facilities')),
                ('family', models.ManyToManyField(blank=True, to='amenities.family')),
                ('heating_and_cooling', models.ManyToManyField(blank=True, to='amenities.heatingandcooling')),
                ('highlights', models.ManyToManyField(blank=True, to='airbnb_app.highlights')),
                ('internet_and_office', models.ManyToManyField(blank=True, to='amenities.internetandoffice')),
                ('kitchen_and_dining', models.ManyToManyField(blank=True, to='amenities.kitchenanddining')),
                ('outdoors', models.ManyToManyField(blank=True, to='amenities.outdoors')),
                ('parking', models.ManyToManyField(blank=True, to='amenities.parking')),
                ('safety', models.ManyToManyField(blank=True, to='amenities.safety')),
                ('services', models.ManyToManyField(blank=True, to='amenities.services')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Property Categories',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/properties')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.property')),
            ],
            options={
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=150)),
                ('review', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.property')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.DeleteModel(
            name='Apt',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='airbnb_app.propertycategory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
