# Generated by Django 4.0.4 on 2022-06-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_booking_city_highlights_property_propertycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1),
        ),
    ]
