# Generated by Django 4.0.4 on 2022-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_booking_property_propertycategory_delete_apt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycategory',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
