# Generated by Django 4.0.4 on 2022-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0003_alter_propertycategory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bathroom',
            },
        ),
        migrations.CreateModel(
            name='KitchenAndDining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kitchen and Dining',
                'verbose_name_plural': 'Kitchen and Dining',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom_objects',
            field=models.ManyToManyField(to='airbnb_app.bathroom'),
        ),
    ]
