# Generated by Django 4.0.4 on 2022-05-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_bathroom_kitchenanddining_alter_property_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bathroom',
            options={'verbose_name_plural': 'Bathroom'},
        ),
        migrations.AlterModelOptions(
            name='kitchenanddining',
            options={'verbose_name_plural': 'Kitchen and Dining'},
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.TextField(),
        ),
    ]
