# Generated by Django 4.0.4 on 2022-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_remove_booking_no_of_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
    ]
