# Generated by Django 4.0.4 on 2022-05-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0006_remove_property_amenities_remove_property_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, upload_to='property'),
        ),
    ]
