# Generated by Django 4.0.4 on 2022-06-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0006_rename_no_of_guests_booking_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='max_days',
            new_name='min_days',
        ),
    ]
