# Generated by Django 4.0.4 on 2022-05-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0007_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
