# Generated by Django 4.0.4 on 2022-05-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0008_alter_property_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.RenameField(
            model_name='property',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='bathroom',
            name='object',
        ),
        migrations.RemoveField(
            model_name='kitchenanddining',
            name='object',
        ),
        migrations.AddField(
            model_name='bathroom',
            name='amenity',
            field=models.CharField(default='amenity', max_length=250),
        ),
        migrations.AddField(
            model_name='kitchenanddining',
            name='amenity',
            field=models.CharField(default='amenity', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.city'),
            preserve_default=False,
        ),
    ]
