# Generated by Django 4.0.4 on 2022-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0009_city_rename_available_property_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='amenity',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='kitchenanddining',
            name='amenity',
            field=models.CharField(default='', max_length=250),
        ),
    ]
