# Generated by Django 4.0.4 on 2022-05-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0012_highlights_remove_property_highlights_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlights',
            old_name='highlght',
            new_name='highlight',
        ),
    ]
