# Generated by Django 4.0.4 on 2022-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('airbnb_app', '0015_alter_property_options_alter_propertyimages_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attractions',
        ),
        migrations.DeleteModel(
            name='Bathroom',
        ),
        migrations.DeleteModel(
            name='Bedroom',
        ),
        migrations.DeleteModel(
            name='Cleaning',
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='HeatingAndCooling',
        ),
        migrations.DeleteModel(
            name='InternetAndOffice',
        ),
        migrations.DeleteModel(
            name='KitchenAndDining',
        ),
        migrations.DeleteModel(
            name='Outdoors',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='Safety',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='property',
            name='attractions',
            field=models.ManyToManyField(blank=True, to='amenities.attractions'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.ManyToManyField(blank=True, to='amenities.bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.ManyToManyField(blank=True, to='amenities.bedroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cleaning',
            field=models.ManyToManyField(blank=True, to='amenities.cleaning'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entertainment',
            field=models.ManyToManyField(blank=True, to='amenities.entertainment'),
        ),
        migrations.AlterField(
            model_name='property',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='amenities.facilities'),
        ),
        migrations.AlterField(
            model_name='property',
            name='family',
            field=models.ManyToManyField(blank=True, to='amenities.family'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating_and_cooling',
            field=models.ManyToManyField(blank=True, to='amenities.heatingandcooling'),
        ),
        migrations.AlterField(
            model_name='property',
            name='highlights',
            field=models.ManyToManyField(blank=True, to='airbnb_app.highlights'),
        ),
        migrations.AlterField(
            model_name='property',
            name='internet_and_office',
            field=models.ManyToManyField(blank=True, to='amenities.internetandoffice'),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen_and_dining',
            field=models.ManyToManyField(blank=True, to='amenities.kitchenanddining'),
        ),
        migrations.AlterField(
            model_name='property',
            name='outdoors',
            field=models.ManyToManyField(blank=True, to='amenities.outdoors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.ManyToManyField(blank=True, to='amenities.parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='safety',
            field=models.ManyToManyField(blank=True, to='amenities.safety'),
        ),
        migrations.AlterField(
            model_name='property',
            name='services',
            field=models.ManyToManyField(blank=True, to='amenities.services'),
        ),
    ]
