# Generated by Django 4.0.4 on 2022-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0016_delete_attractions_delete_bathroom_delete_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
