# Generated by Django 4.0.4 on 2022-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0017_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
