# Generated by Django 4.0.4 on 2022-05-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0017_alter_property_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('id',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, upload_to='images/properties'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='images',
            field=models.FileField(upload_to='images/properties'),
        ),
    ]
