# Generated by Django 4.0.4 on 2022-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0018_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('id',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, upload_to='properties'),
        ),
    ]
