# Generated by Django 4.0.4 on 2022-06-05 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airbnb_app', '0018_alter_city_options_alter_property_options_city_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='property_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
